### ISSUE TITLE
[Suggestion] Use an HttpListener for Authentication redirect

### ISSUE THREAD

**Issue by AngelMunoz** [NicoVIII/Andromeda-for-GOG#53]
Hey it's me again 😁

Not sure if the Authentications methods for GOG allow redirecting to custom URLs on localhost but here's my suggestion.

Inside the core Library add an Auth Module which has a type that uses an HttpListener to lift a really small webserver to listen for any visit. if the GOG authentication goes alright it should re-direct you to your "website" with the auth code on the URL, use that small webserver to grab the code and perform any persistence needed once the auth code is accepted and validated (either char length or something) you can just show a "You can close this window now, and you should be logged into Andromeda For Gog" and then stop the HttpListener I have put a small Sample [here](https://github.com/AngelMunoz/SimpleHttpListener/blob/master/Program.fs)

and this is kind of what It can look like
![image](https://user-images.githubusercontent.com/8684875/84530249-095c2500-aca0-11ea-956c-e52e08a4b2de.png)

If GOG accepts redirect URLs I think this could be a way to remove some windows from the app (I don't have anything against windows but I feel in FuncUI they kind of complicate stuff some times)

Let me know what you think

**Comment by NicoVIII** [comment]
Hmm, I didn't thought of that... I kinda hoped I have an embedded browser to do this stuff and parse the result code from there, but this idea sounds awesome!

I will definitely try that, because it could simplify authentication and this is the first step one has to do :smile:

Thanks! That will be a great opportunity to experiment :)

**Comment by AngelMunoz** [comment]
> I kinda hoped I have an embedded browser to do this stuff and parse the result code from there

Yeah I get you... the lack of a "webview" in Avalonia really hurts a bit 😔

**Comment by NicoVIII** [comment]
I wanted to have a look at this, this looks like you could use CefGlue for Avalonia somehow:
https://gitlab.com/joaompneves/cefglue/

But I don't know :smile:

**Comment by NicoVIII** [comment]
I took some stuff from #54 but the main point of this issue is sadly not doable for now. The GOG API is an inofficial one and does not allow to register apps and redirect urls. So the approach with a HttpListener seems impossible.

I close this issue for now, but I will further look into the whole authentication workflow and see, if I can make some version of a browser control work for me.
